name: Package Release
on: [workflow_dispatch]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
          cache: npm
      - name: npm install
        run: npm install
      - name: npm run make
        run: npm run make
      - name: upload to release
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: windows
          path: ./out/make/squirrel.windows/x64/*Setup.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}
