name: Package Release
on:
  release:
    types:
      - released

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20
          cache: npm
      - name: npm install
        run: npm install
      - name: npm run make
        run: npm run make
      - name: create release and upload
      - uses: d1ceward/release-upload-action@v4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./out/make/squirrel.windows/x64/techobot2-${{github.ref_name}} Setup.exe
